# action.yaml
name: 'Run Vault Check'
description: 'A GitHub Action that runs tests against Vault policies.'
inputs:
  directory:
    description: 'Directory where policies can be found.'
    required: true
  dev-server:
    description: 'Whether to use a dev Vault instance. Set to true or false.'
    required: true
    default: 'true'
outputs:
  test_results:
    description: 'Json of test results.'
    # need to specify the extra `value` field for `composite` actions
    value: ${{ steps.run-tests.outputs.test_results }}
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  
    - name: Install Dependencies
      run: pip install -r requirements.txt
      shell: bash
    - name: Pass Inputs to Shell
      run: |
              echo "TEST_DIRECTORY=${{ inputs.directory }}" >> $GITHUB_ENV
              echo "DEV_SERVER=${{ inputs.dev-server }}" >> $GITHUB_ENV
      shell: bash
    - name: Run policy tests
      id: run-tests
      env:
        VAULT_ADDR: 'http://127.0.0.1:8200'
        VAULT_TOKEN: '1234567890qwertyuiopASDFGHJKL'
      run: |
              echo "{test_results}={$(python test_capabilities.py -d $TEST_DIRECTORY)}" >> $GITHUB_OUTPUT

      shell: bash