# action.yaml
name: 'Run Vault Check'
description: 'A GitHub Action that runs tests against Vault policies.'
inputs:
  directory:
    description: 'Directory where policies can be found.'
    required: true
  dev-server:
    description: 'Whether to use a dev Vault instance. Set to true or false.'
    required: true
    default: 'true'
outputs:
  test_results:
    description: 'Json of test results.'
    # need to specify the extra `value` field for `composite` actions
    value: ${{ steps.run-tests.outputs.test_results }}
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  
    - name: Install Dependencies
      run: pip install -r requirements.txt
      shell: bash
    - name: Pass Inputs to Shell
      run: |
              echo "TEST_DIRECTORY=${{ inputs.directory }}" >> $GITHUB_ENV
              echo "DEV_SERVER=${{ inputs.dev-server }}" >> $GITHUB_ENV
      shell: bash
    - name: Install Vault
      id: install-vault
      shell: bash
      run: |
            sudo apt update && sudo apt install gpg -y
            wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
            sudo apt update && sudo apt install vault -y
    - name: Run policy tests
      id: run-tests
      run: python test_capabilities.py -d $TEST_DIRECTORY -v
      shell: bash