name: 'Vault Policy Checks'

on: [pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        name: 'CI Checks'
        services:
            vault:
                image: hashicorp/vault
                env:
                    VAULT_DEV_ROOT_TOKEN_ID: '1234567890qwertyuiopASDFGHJKL'
                ports:
                    - 8200:8200
        steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name: Run Vault Tests
            id: vault-tests
            uses: ./
            with:
                directory: 'policies'
                vault_token: '1234567890qwertyuiopASDFGHJKL'
          - name: Convert JSON to Table
            id: table
            uses: buildingcash/json-to-markdown-table-action@v1
            with:
              json: ${{ steps.vault-tests.outputs.test_results }}
          - name: Add Result Comment
            id: comment
            uses: thollander/actions-comment-pull-request@v2
            with:
              message: |
                ${{ steps.table.outputs.table }}
