name: 'CI Checks'

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        name: 'CI Checks'
        container:
            image: hashicorp/vault
            env:
                VAULT_DEV_ROOT_TOKEN_ID: '1234567890qwertyuiopASDFGHJKL'
            ports:
                - 8200
        steps:
          - name: Checkout
            uses: actions/checkout@v2
          #- name: Run Vault Tests
          #  id: vault-tests
          #  uses: ./
          #  with:
          #      directory: 'policies'
          #- name: Print Results
          #  run: |
          #      echo "Results: ${{ steps.vault-tests.outputs.results }}"
          - name: Vault Commands
            run: |
              curl http://127.0.0.1:8200/v1/sys/health
        

