name: 'CI Checks'

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        name: 'CI Checks'
        defaults:
            run:
                shell: bash
        container:
            image: hashicorp/vault
            env:
                VAULT_DEV_ROOT_TOKEN_ID: '1234567890qwertyuiopASDFGHJKL'
            ports:
                - 8200
        steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name: Run Vault Tests
            id: vault-tests
            uses: ./
            with:
                directory: 'policies'
          - name: Print Results
            run: |
                echo "Results: ${{ steps.vault-tests.outputs.results }}"

